import React from 'react';
import { Copy, Download, RefreshCw, Trash2, Check } from 'lucide-react';
import { useState } from 'react';

interface QuickActionsProps {
  onClear: () => void;
  onAnalyzeAnother: () => void;
  result: any;
}

const QuickActions: React.FC<QuickActionsProps> = ({ onClear, onAnalyzeAnother, result }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const text = `PhishGuard AI Analysis Report
Classification: ${result.classification}
Risk Score: ${result.risk_score}/100
Recommendation: ${result.recommendation}
Generated by PhishGuard AI`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(result, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href",     dataStr);
    downloadAnchorNode.setAttribute("download", "phishguard_report.json");
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={handleCopy}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white text-xs font-bold transition-all"
      >
        {copied ? <Check className="w-3.5 h-3.5 text-success" /> : <Copy className="w-3.5 h-3.5" />}
        {copied ? 'Copied!' : 'Copy Summary'}
      </button>
      <button
        onClick={handleExportJSON}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white text-xs font-bold transition-all"
      >
        <Download className="w-3.5 h-3.5" />
        Export JSON
      </button>
      <button
        onClick={onAnalyzeAnother}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-accent-primary/10 border border-accent-primary/20 hover:bg-accent-primary/20 text-accent-primary text-xs font-bold transition-all"
      >
        <RefreshCw className="w-3.5 h-3.5" />
        New Scan
      </button>
      <button
        onClick={onClear}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-danger/10 border border-danger/20 hover:bg-danger/20 text-danger text-xs font-bold transition-all"
      >
        <Trash2 className="w-3.5 h-3.5" />
        Clear
      </button>
    </div>
  );
};

export default QuickActions;
